//! High-quality output generation (XML is the primary recommended format for LLMs).
//!
//! Follows repomix / Anthropic best practices for XML-tagged context.

use std::io::Write;
use std::path::Path;

use crate::core::walker::{normalize_rel_path, DirEntryMeta};
use content_inspector;
use encoding_rs;
use serde_json::{json, Value};

/// Default per-file size limit when the caller does not specify one.
pub const DEFAULT_MAX_FILE_SIZE: u64 = 2 * 1024 * 1024; // 2 MiB

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum OutputFormat {
    #[default]
    Xml,
    Markdown,
    Json,
    Plain,
}

/// Options for packing files into LLM-ready text.
#[derive(Clone, Debug)]
pub struct WriteOptions {
    pub format: OutputFormat,
    pub include_file_summary: bool,
    pub max_file_size: u64,
}

impl Default for WriteOptions {
    fn default() -> Self {
        Self {
            format: OutputFormat::Xml,
            include_file_summary: true,
            max_file_size: DEFAULT_MAX_FILE_SIZE,
        }
    }
}

/// Main high-quality writer.
pub fn write_output<W: Write>(
    writer: &mut W,
    entries: &[DirEntryMeta],
    root: &Path,
    options: &WriteOptions,
) -> std::io::Result<()> {
    let files: Vec<_> = entries.iter().filter(|e| !e.is_dir).collect();

    match options.format {
        OutputFormat::Xml => write_xml(writer, &files, root, options),
        OutputFormat::Markdown => write_markdown(writer, &files, root, options),
        OutputFormat::Json => write_json(writer, &files, root, options),
        OutputFormat::Plain => write_plain(writer, &files, root, options),
    }
}

fn display_path(path: &Path) -> String {
    normalize_rel_path(path)
}

fn escape_xml_attr(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&apos;"),
            c if c.is_control() && c != '\t' && c != '\n' && c != '\r' => {
                // Strip illegal XML 1.0 control chars from attributes
            }
            c => out.push(c),
        }
    }
    out
}

/// Write text inside a CDATA section, safely splitting on the `]]>` terminator.
fn write_cdata<W: Write>(w: &mut W, content: &str) -> std::io::Result<()> {
    writeln!(w, "      <![CDATA[")?;
    // XML forbids `]]>` inside CDATA; split and re-open sections.
    let mut rest = content;
    while let Some(idx) = rest.find("]]>") {
        write!(w, "{}]]]]><![CDATA[>", &rest[..idx])?;
        rest = &rest[idx + 3..];
    }
    write!(w, "{rest}")?;
    writeln!(w, "\n      ]]>")?;
    Ok(())
}

fn write_xml<W: Write>(
    w: &mut W,
    files: &[&DirEntryMeta],
    root: &Path,
    options: &WriteOptions,
) -> std::io::Result<()> {
    let root_disp = escape_xml_attr(&root.display().to_string());
    writeln!(w, "<project_context>")?;
    writeln!(
        w,
        "  <source>This file was generated by ptt (ProjectToText) from {root_disp}</source>"
    )?;
    writeln!(w, "  <instruction>Below is the complete (curated) content of the project. Use it for code analysis, refactoring, or implementation tasks.</instruction>")?;
    writeln!(
        w,
        "  <reading_info>Files were read respecting .gitignore (and .pttignore if present). Large files (&gt;{} bytes) and binaries are replaced with notes. Text files decoded preferring UTF-8.</reading_info>",
        options.max_file_size
    )?;

    if options.include_file_summary {
        writeln!(w, "  <file_summary>")?;
        writeln!(w, "    Total files included: {}", files.len())?;
        let total_size: u64 = files.iter().filter_map(|f| f.size).sum();
        writeln!(w, "    Total size: {total_size} bytes")?;
        writeln!(
            w,
            "    Note: File contents were read with size limits ({} bytes max), binary detection, and encoding handling (UTF-8 primary with fallbacks).",
            options.max_file_size
        )?;
        writeln!(w, "  </file_summary>")?;
    }

    writeln!(w, "  <directory_structure>")?;
    for f in files {
        writeln!(w, "    {}", display_path(&f.path))?;
    }
    writeln!(w, "  </directory_structure>")?;

    writeln!(w, "  <files>")?;
    for f in files {
        let full_path = root.join(&f.path);
        let content = read_file_content(&full_path, options.max_file_size);
        let path_attr = escape_xml_attr(&display_path(&f.path));

        writeln!(w, "    <file path=\"{path_attr}\">")?;
        write_cdata(w, &content)?;
        writeln!(w, "    </file>")?;
    }
    writeln!(w, "  </files>")?;
    writeln!(w, "</project_context>")?;
    Ok(())
}

fn write_markdown<W: Write>(
    w: &mut W,
    files: &[&DirEntryMeta],
    root: &Path,
    options: &WriteOptions,
) -> std::io::Result<()> {
    writeln!(w, "# Project Context")?;
    writeln!(w, "Generated from: `{}`", root.display())?;
    writeln!(
        w,
        "Reading info: Files processed with size/binary limits (max {} bytes) and encoding handling.\n",
        options.max_file_size
    )?;

    for f in files {
        let full = root.join(&f.path);
        let content = read_file_content(&full, options.max_file_size);
        let ext = f.path.extension().and_then(|e| e.to_str()).unwrap_or("");
        let path = display_path(&f.path);

        // Fence language from extension; avoid breaking fences if content has ```
        let fence = if content.contains("```") {
            "~~~~"
        } else {
            "```"
        };

        writeln!(w, "## `{path}`")?;
        writeln!(w, "{fence}{ext}")?;
        writeln!(w, "{content}")?;
        writeln!(w, "{fence}")?;
        writeln!(w)?;
    }
    Ok(())
}

fn write_json<W: Write>(
    w: &mut W,
    files: &[&DirEntryMeta],
    root: &Path,
    options: &WriteOptions,
) -> std::io::Result<()> {
    let file_objs: Vec<Value> = files
        .iter()
        .map(|f| {
            let full = root.join(&f.path);
            let content = read_file_content(&full, options.max_file_size);
            json!({
                "path": display_path(&f.path),
                "size": f.size,
                "content": content,
            })
        })
        .collect();

    let doc = json!({
        "generator": "ptt (ProjectToText)",
        "root": root.display().to_string(),
        "reading_info": format!(
            "Files read with {} byte limit, binary detection, encoding handling (UTF-8 primary).",
            options.max_file_size
        ),
        "file_count": files.len(),
        "files": file_objs,
    });

    let pretty = serde_json::to_string_pretty(&doc)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;
    writeln!(w, "{pretty}")?;
    Ok(())
}

fn write_plain<W: Write>(
    w: &mut W,
    files: &[&DirEntryMeta],
    root: &Path,
    options: &WriteOptions,
) -> std::io::Result<()> {
    writeln!(w, "Project: {}", root.display())?;
    writeln!(
        w,
        "Reading info: Data read with limits ({} bytes), binary skip, UTF-8+fallback.",
        options.max_file_size
    )?;
    writeln!(w, "================================\n")?;

    for f in files {
        let full = root.join(&f.path);
        let content = read_file_content(&full, options.max_file_size);
        writeln!(w, ">>> {}", display_path(&f.path))?;
        writeln!(w, "{content}")?;
        writeln!(w, "--------------------------------\n")?;
    }
    Ok(())
}

fn read_file_content(path: &Path, max_file_size: u64) -> String {
    let meta = match std::fs::metadata(path) {
        Ok(m) => m,
        Err(e) => return format!("[Error reading metadata: {e}]"),
    };

    let file_size = meta.len();
    if file_size > max_file_size {
        return format!("[File too large: {file_size} bytes (limit {max_file_size}), skipped]");
    }

    match std::fs::read(path) {
        Ok(bytes) => {
            let sample_len = bytes.len().min(8192);
            let is_binary =
                bytes.contains(&0) || content_inspector::inspect(&bytes[..sample_len]).is_binary();

            if is_binary {
                return format!(
                    "[Binary file - {file_size} bytes, content omitted for LLM safety]"
                );
            }

            let (decoded, encoding_used, had_errors) = encoding_rs::UTF_8.decode(&bytes);
            let content = decoded.to_string();

            format!(
                "// [ptt read info] size={file_size} bytes, encoding={}, replacement_chars={had_errors}\n{content}",
                encoding_used.name(),
            )
        }
        Err(e) => format!("[Error reading file: {e}]"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::path::PathBuf;

    fn tmp_project() -> (tempfile::TempDir, PathBuf) {
        let dir = tempfile::tempdir().expect("tempdir");
        let root = dir.path().to_path_buf();
        fs::write(root.join("hello.rs"), "fn main() {}\n").unwrap();
        fs::write(root.join("notes.md"), "hello ]]> world\n").unwrap();
        (dir, root)
    }

    fn entries_for(root: &Path) -> Vec<DirEntryMeta> {
        vec![
            DirEntryMeta {
                path: PathBuf::from("hello.rs"),
                is_dir: false,
                size: Some(12),
            },
            DirEntryMeta {
                path: PathBuf::from("notes.md"),
                is_dir: false,
                size: Some(14),
            },
        ]
        // silence unused if needed
        .into_iter()
        .map(|mut e| {
            if let Ok(m) = fs::metadata(root.join(&e.path)) {
                e.size = Some(m.len());
            }
            e
        })
        .collect()
    }

    #[test]
    fn json_is_valid_and_roundtrips() {
        let (_dir, root) = tmp_project();
        let entries = entries_for(&root);
        let mut buf = Vec::new();
        let opts = WriteOptions {
            format: OutputFormat::Json,
            include_file_summary: true,
            max_file_size: DEFAULT_MAX_FILE_SIZE,
        };
        write_output(&mut buf, &entries, &root, &opts).unwrap();
        let v: Value = serde_json::from_slice(&buf).expect("valid JSON");
        assert_eq!(v["file_count"], 2);
        assert!(v["files"].as_array().unwrap().len() == 2);
        let content = v["files"][0]["content"].as_str().unwrap();
        assert!(content.contains("fn main") || content.contains("hello"));
    }

    #[test]
    fn xml_escapes_cdata_terminator() {
        let (_dir, root) = tmp_project();
        let entries = entries_for(&root);
        let mut buf = Vec::new();
        let opts = WriteOptions {
            format: OutputFormat::Xml,
            include_file_summary: true,
            max_file_size: DEFAULT_MAX_FILE_SIZE,
        };
        write_output(&mut buf, &entries, &root, &opts).unwrap();
        let s = String::from_utf8(buf).unwrap();
        // Raw `]]>` must not appear unescaped inside a single CDATA block
        assert!(s.contains("]]]]><![CDATA[>"));
        assert!(s.contains("<project_context>"));
        assert!(s.contains("path=\"notes.md\""));
    }

    #[test]
    fn xml_escapes_attribute_special_chars() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        // Unusual but legal filename characters for attr escape test via synthetic entry
        let path = PathBuf::from("a&b<c>.rs");
        fs::write(root.join("a&b<c>.rs"), "x").unwrap();
        let entries = vec![DirEntryMeta {
            path: path.clone(),
            is_dir: false,
            size: Some(1),
        }];
        let mut buf = Vec::new();
        let opts = WriteOptions {
            format: OutputFormat::Xml,
            ..Default::default()
        };
        write_output(&mut buf, &entries, root, &opts).unwrap();
        let s = String::from_utf8(buf).unwrap();
        assert!(s.contains("path=\"a&amp;b&lt;c&gt;.rs\""));
    }

    #[test]
    fn respects_max_file_size() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        fs::write(root.join("big.txt"), "abcdefghij").unwrap(); // 10 bytes
        let entries = vec![DirEntryMeta {
            path: PathBuf::from("big.txt"),
            is_dir: false,
            size: Some(10),
        }];
        let mut buf = Vec::new();
        let opts = WriteOptions {
            format: OutputFormat::Plain,
            include_file_summary: false,
            max_file_size: 5,
        };
        write_output(&mut buf, &entries, root, &opts).unwrap();
        let s = String::from_utf8(buf).unwrap();
        assert!(s.contains("File too large"));
        assert!(!s.contains("abcdefghij"));
    }

    #[test]
    fn markdown_handles_nested_fences() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        fs::write(root.join("doc.md"), "```\ncode\n```\n").unwrap();
        let entries = vec![DirEntryMeta {
            path: PathBuf::from("doc.md"),
            is_dir: false,
            size: Some(12),
        }];
        let mut buf = Vec::new();
        let opts = WriteOptions {
            format: OutputFormat::Markdown,
            ..Default::default()
        };
        write_output(&mut buf, &entries, root, &opts).unwrap();
        let s = String::from_utf8(buf).unwrap();
        assert!(s.contains("~~~~"));
    }

    #[test]
    fn escape_xml_attr_basics() {
        assert_eq!(escape_xml_attr(r#"a&b"c"#), "a&amp;b&quot;c");
    }
}
